version: "3.8"

services:
  django:
    build: .
    container_name: django_2
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery_2
    command: celery -A netauto worker --loglevel INFO
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis

  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_DATABASE: netauto_djongo_db
    ports:
      - "27017:27017"
    volumes:
      - /data/db

volumes:
  mongo: